// ReportsPage.js
import React from 'react';


const ReportsPage = () => {
  return (
    <div>
      <h2>Reports</h2>
      <p>This is the Reports page. Here you can view various reports generated by the system.</p>
      <ul>
        <li>Report 1: User Activity</li>
        <li>Report 2: Group Statistics</li>
        <li>Report 3: Access Logs</li>
      </ul>
    </div>
  );
};

export default ReportsPage;
